---
- name: Add Grafana APT repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: Update APT cache
  apt:
    update_cache: yes



- name: Add data sources and dashboards
  command: /usr/bin/grafana-cli --etc /etc/grafana add-datasource

- name: Install Grafana
  apt:
    name: grafana
    state: present
  notify:
    - Restart Grafana

- name: Ensure Grafana is running
  systemd:
    name: grafana-server
    state: started
    enabled: yes
