---
- name: Add Grafana APT repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Find grafana-cli
  stat:
    path: /usr/share/grafana/bin/grafana-cli
  register: grafana_cli

- name: Set grafana_cli_path
  set_fact:
    grafana_cli_path: "{{ grafana_cli.stat.exists | ternary('/usr/share/grafana/bin/grafana-cli', '/usr/bin/grafana-cli') }}"

- name: Add data sources and dashboards
  command: "{{ grafana_cli_path }} --etc /etc/grafana add-datasource"
  register: grafana_cli_output
  ignore_errors: yes
  
- name: Install Grafana
  apt:
    name: grafana
    state: present
  notify:
    - Restart Grafana

- name: Ensure Grafana is running
  systemd:
    name: grafana-server
    state: started
    enabled: yes
