---
- hosts: localhost
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        path: /usr/local/grafana
        state: directory
        mode: '0755'

    - name: Download Grafana tarball
      get_url:
        url: https://dl.grafana.com/oss/release/grafana-11.1.3.linux-amd64.tar.gz
        dest: /tmp/grafana-11.1.3.linux-amd64.tar.gz

    - name: Extract Grafana tarball
      unarchive:
        src: /tmp/grafana-11.1.3.linux-amd64.tar.gz
        dest: /usr/local/grafana
        remote_src: yes
        creates: /usr/local/grafana/grafana-11.1.3

    - name: Create symlink for Grafana binary
      file:
        src: /usr/local/grafana/grafana-11.1.3/bin/grafana-server
        dest: /usr/local/bin/grafana-server
        state: link

    - name: Create symlink for Grafana CLI binary
      file:
        src: /usr/local/grafana/grafana-11.1.3/bin/grafana-cli
        dest: /usr/local/bin/grafana-cli
        state: link

    - name: Create Grafana data directory
      file:
        path: /var/lib/grafana
        state: directory
        mode: '0755'

    - name: Create Grafana log directory
      file:
        path: /var/log/grafana
        state: directory
        mode: '0755'

    - name: Create Grafana config directory
      file:
        path: /etc/grafana
        state: directory
        mode: '0755'

    - name: Copy Grafana configuration file
      copy:
        src: /usr/local/grafana/grafana-11.1.3/conf/defaults.ini
        dest: /etc/grafana/grafana.ini
        remote_src: yes

    - name: Set up Grafana as a systemd service
      copy:
        content: |
          [Unit]
          Description=Grafana instance
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/grafana-server \
            --config=/etc/grafana/grafana.ini \
            --homepath=/usr/local/grafana/grafana-11.1.3
          User=grafana
          Group=grafana
          Restart=always
          WorkingDirectory=/usr/local/grafana/grafana-11.1.3

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/grafana.service

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable Grafana service
      systemd:
        name: grafana
        enabled: yes

    - name: Start Grafana service
      systemd:
        name: grafana
        state: started

    - name: Find grafana-cli
      stat:
        path: /usr/local/grafana/grafana-11.1.3/bin/grafana-cli
      register: grafana_cli

    - name: Set grafana_cli_path
      set_fact:
        grafana_cli_path: "{{ grafana_cli.stat.exists | ternary('/usr/local/grafana/grafana-11.1.3/bin/grafana-cli', '/usr/bin/grafana-cli') }}"

    - name: Add data sources and dashboards
      command: "{{ grafana_cli_path }} --config /etc/grafana/grafana.ini add-datasource"
      register: grafana_cli_output
      ignore_errors: yes
