- hosts: localhost
  become: yes
  roles:
    - role: /home/ubuntu/.ansible/pull/DeployBuddy/apps/backend/src/ansible/roles/prometheus
    - role: /home/ubuntu/.ansible/pull/DeployBuddy/apps/backend/src/ansible/roles/grafana
    - role: /home/ubuntu/.ansible/pull/DeployBuddy/apps/backend/src/ansible/roles/elk
  